# Generated by Django 5.1.5 on 2025-02-13 03:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Planner",
            fields=[
                ("plan_no", models.AutoField(primary_key=True, serialize=False)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("plan_img", models.CharField(blank=True, max_length=200)),
                ("sdate", models.DateField(blank=True, null=True)),
                ("edate", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=50)),
                ("birth", models.DateField(blank=True, null=True)),
                ("addr", models.CharField(blank=True, max_length=200)),
                ("phone_num", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tourlist",
            fields=[
                (
                    "title",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("addr1", models.CharField(blank=True, max_length=200)),
                ("areacode", models.IntegerField(blank=True, null=True)),
                ("sigungucode", models.IntegerField(blank=True, null=True)),
                ("image2", models.CharField(blank=True, max_length=200)),
                ("readcount", models.IntegerField(default=0)),
                ("ping", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="planner.board",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="planner.signup"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="board",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planner.signup"
            ),
        ),
        migrations.CreateModel(
            name="PlannerDetail",
            fields=[
                ("pd_no", models.AutoField(primary_key=True, serialize=False)),
                ("plan_name", models.CharField(max_length=200)),
                ("wdate", models.CharField(blank=True, max_length=200, null=True)),
                ("memo", models.TextField(blank=True)),
                (
                    "planner",
                    models.ForeignKey(
                        db_column="planner_fk",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.planner",
                    ),
                ),
                (
                    "signup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="planner.signup"
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.tourlist",
                    ),
                ),
            ],
        ),
    ]
