# Generated by Django 5.1.5 on 2025-02-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannerdetail",
            name="actual_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
