# Generated by Django 5.1.5 on 2025-02-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
