# Generated by Django 5.1.5 on 2025-02-18 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="feed_images/"),
                ),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="planner.signup"
                    ),
                ),
                (
                    "bookmarks",
                    models.ManyToManyField(
                        blank=True, related_name="bookmarked_feeds", to="planner.signup"
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True, related_name="liked_feeds", to="planner.signup"
                    ),
                ),
            ],
        ),
    ]
